#!/bin/bash
clear
echo -e "\033[1;31m"
echo -e ""
echo -e "PLUS-DESK VIDEO CONVERTER 2020"
echo -e "\033[3;90mPowered by: FFMPEG"
echo -e "\033[0m"
echo -e "This will convert all mp4, mov, avi, gif and mxf-files in the folder for web use and generates posters for them."
echo -e ""
echo -e "Current folder:\033[4;39m"
pwd
echo -e "\033[1;39m"
echo -e "Use default settings?\033[7;39m"
read -p "[y]/n?" defaultchoice
[ -z "${defaultchoice}" ] && defaultchoice='y'
echo -e "User choice: $defaultchoice"
clear
if [ $defaultchoice == "n" ]
then
    echo -e "\033[1;31m"
    echo -e "Custom settings (1/3)"
    echo -e "\033[0m"
    echo -e ""
    echo -e "Resolution [default: 1, enter to skip]"
    echo -e "\033[7;39m"
    read -p "1: 1080p | 2: 720p | 3: Both " resolution
    clear
    echo -e "\033[1;31m"
    echo -e "Custom settings (2/3)"
    echo -e "\033[0m"
    echo -e ""
    echo -e "Compression [default: 1, enter to skip]"
    echo -e "\033[7;39m"
    read -p "1: 26 | 2: Lossless | 3: Custom " bitrate
    clear
    echo -e "\033[1;31m"
    echo -e "Custom settings (3/3)"
    echo -e "\033[0m"
    echo -e ""
    echo -e "Encoding speed [default: 1, enter to skip]"
    echo -e "\033[7;39m"
    read -p "1: Medium | 2: Slowest (best compression) | 3: Fastest " speed
    clear

fi
[ -z "${resolution}" ] && resolution="1"
[ -z "${bitrate}" ] && bitrate="1"
[ -z "${speed}" ] && speed="1"

obitrate="-crf 26 -maxrate 8M -bufsize 6M "
ospeed="-preset slower "

if [[ $bitrate -eq 2 ]]
then
    obitrate="-crf 10 "
elif [[ $bitrate -eq 3 ]]
then
    echo -e "\033[7;39m"
    read -p "Custom compression (0-51): " cbitrate
    obitrate="-crf $cbitrate "
fi

if [[ $speed -eq 2 ]]
then
    ospeed="-preset veryslow "
elif [[ $speed -eq 3 ]]
then
    ospeed="-preset fast "
fi

echo -e "\033[0mConverting following files:"
shopt -s nullglob
for i in *.mp4 *.mov *.mxf *.avi *.gif
do
    echo -e $i
done
echo -e ""
echo -e "Options:"
echo -e $ospeed
echo -e $obitrate
echo -e $resolution
echo -e ""
echo -e "Continue?\033[7;39m"
read -p "[y]/n?" contconv
[ -z "${contconv}" ] && contconv='y'
clear
if [ $contconv == "y" ]
then
    ffmpegdir="ffmpeg" 
    if [ ! -d "$ffmpegdir" ]
    then
        echo -e "\033[0mCreating folder..."
        mkdir ffmpeg
        mkdir ffmpeg/1080p
        mkdir ffmpeg/720p

    else
        echo -e "\033[1;0mExisting files detected. Overwrite?"
        read -p "[y]/n?" overwrite
        [ -z "${overwrite}" ] && overwrite='y'
        if [ $overwrite == "n" ]
        then
        echo -e "\033[1;39mThank you for using \033[1;31mPLUS-DESK VIDEO CONVERTER 2020!\033[0m"
        exit
        fi
        mkdir ffmpeg/1080p
        mkdir ffmpeg/720p

    fi
    echo -e "\033[1;0mCONVERTING..."
    if [ $resolution -eq 1 ] || [ $resolution -eq 3 ]
    then
        echo -e "1080p PIPE"
        shopt -s nullglob
        for i in *.mp4 *.mov *.mxf *.avi *.gif
            do
                ffmpeg -y -i $i -vf scale=-1:1080 -c:v libx264 $obitrate -vf format=yuv420p ${ospeed}ffmpeg/1080p/${i%.*}.mp4
                ffmpeg -y -i $i -ss 00:00:00.001 -vframes 1 ffmpeg/1080p/${i}.poster.jpg
        done
    fi
    if [ $resolution -eq 2 ] || [ $resolution -eq 3 ]
    then
        echo -e "720P PIPE"
        shopt -s nullglob
        for i in *.mp4 *.mov *.mxf *.avi *.gif
            do
                ffmpeg -y -i $i -vf scale=-1:720 -c:v libx264 ${ospeed}ffmpeg/720p/${i%.*}.mp4
                ffmpeg -y -i $i -ss 00:00:00.001 -vframes 1 ffmpeg/1080p/${i}.poster.jpg
        done
    fi
fi

echo -e "Thank you for using \033[1;31mPLUS-DESK VIDEO CONVERTER 2020!\033[0m"
exit